version: '3.8'

services:
  db:
    image: postgres:15
    container_name: sgev_db
    restart: always
    environment:
      POSTGRES_USER: lily_admin
      POSTGRES_PASSWORD: senha_segura_123
      POSTGRES_DB: sgev_estoque
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: